[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyisland-toast"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pigar>=2.2.0",
    "pyside6>=6.11.2",
    "windows-bluetooth-watcher",
]

[project.scripts]
pyisland-toast = "pyisland_toast.app:main"
